import { AppComponent } from "./components/app";
import { LandingComponent } from "./components/landing/landing";
import { skillsComponent } from "./components/skills/skills";
import { NavComponent } from "./components/nav/nav";
import { FooterComponent } from "./components/footer/footer";
import { SkillSetComponent } from "./components/skills/skill-set/skill-set";
import { SkillBarComponent } from "./components/skills/skill-bar/skill-bar";
import { ContactFormComponent } from "./components/footer/contact-form/contact-form";
import { FooterLinksComponent } from "./components/footer/footer-links/footer-links";
